name: e2e

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-22.04
    steps:
      - name: Java Diagnostics
        run: |
          echo "=== Java Alternatives ==="
          ls -al /etc/alternatives
          echo -e "\n=== Java Security Files ==="
          find /usr/lib/jvm -name "java.security"
          echo -e "\n=== Java Security Directories ==="
          find /usr/lib/jvm -name "security" -type d
          echo -e "\n=== Java Security Symlinks ==="
          find /usr/lib/jvm -type l -name "java.security" -o -name "java.policy" -o -name "nss.cfg" -o -name "default.policy" -o -name "blocked.certs"
          echo -e "\n=== Java Installation Details ==="
          update-java-alternatives --list
          echo -e "\n=== Java Version ==="
          java -version
          echo -e "\n=== Java Security Properties ==="
          java -Djava.security.debug=properties -version
